version: "3.8"

services:
  nginx:
    build: ./nginx
    image: nginx:custom
    container_name: nginx_cont
    ports:
      - "80:80"
    depends_on:
      - django_app
    restart: always
    networks:
      - notes-app-nw

  django_app:
    build:
      context: .
    image: django_app:latest
    container_name: django_cont
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py migrate --noinput &&
             gunicorn notesapp.wsgi:application --bind 0.0.0.0:8000"
    environment:
      DEBUG: "False"
      DJANGO_SECRET_KEY: "your_secret_key_here"
      DATABASE_NAME: "test_db"
      DATABASE_USER: "root"
      DATABASE_PASSWORD: "root"
      DATABASE_HOST: "db"
      DATABASE_PORT: "3306"
    depends_on:
      - db
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/admin || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - notes-app-nw

  db:
    image: mysql:5.7
    container_name: db_cont
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
    volumes:
      - ./data/mysql/db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
    networks:
      - notes-app-nw

networks:
  notes-app-nw:

